// <auto-generated />
using System;
using CistacApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CistacApp.Migrations
{
    [DbContext(typeof(CistacDbContext))]
    [Migration("20250522113731_InitialCreateSqlite")]
    partial class InitialCreateSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CistacApp.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("BookingID");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Booking_Status");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Check_In_Date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Check_Out_Date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelID");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PaymentID");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD091BC9C2");

                    b.HasIndex("HotelId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CistacApp.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("EMail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("eMail");

                    b.Property<string>("HotelAmenities")
                        .HasColumnType("TEXT")
                        .HasColumnName("Hotel_Amenities");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone_Number");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.HasKey("HotelId")
                        .HasName("PK__Hotels__46023BBF2AAF9269");

                    b.HasIndex(new[] { "EMail" }, "UQ__Hotels__410EDA2F9ECB1D46")
                        .IsUnique();

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("CistacApp.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PaymentID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Payment_Method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Payment_Status");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Transaction_Date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A582B4EC6D7");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CistacApp.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PromotionID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Discount_Percentage");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("Valid_From");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("Valid_To");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42F2F9BCD3B64");

                    b.HasIndex("HotelId");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("CistacApp.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReviewID");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AEBF50D19F");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CistacApp.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomID");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Available")
                        .HasColumnName("Availability_Status");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelID");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Price_Per_Night");

                    b.Property<string>("RoomAmenities")
                        .HasColumnType("TEXT")
                        .HasColumnName("Room_Amenities");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Room_Number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.HasKey("RoomId")
                        .HasName("PK__Rooms__32863919689C63C6");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CistacApp.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("StaffID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("EMail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("eMail");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone_Number");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.HasKey("StaffId")
                        .HasName("PK__Staff__96D4AAF76F483233");

                    b.HasIndex("HotelId");

                    b.HasIndex(new[] { "EMail" }, "UQ__Staff__410EDA2FBB11187F")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("CistacApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("eMail");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone_Number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated_At");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACD915F11F");

                    b.HasIndex(new[] { "EMail" }, "UQ__Users__410EDA2F7A52129C")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CistacApp.Models.Booking", b =>
                {
                    b.HasOne("CistacApp.Models.Hotel", "Hotel")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Hotels");

                    b.HasOne("CistacApp.Models.Payment", "Payment")
                        .WithMany("Bookings")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_Bookings_Payments");

                    b.HasOne("CistacApp.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Rooms");

                    b.HasOne("CistacApp.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Users");

                    b.Navigation("Hotel");

                    b.Navigation("Payment");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CistacApp.Models.Payment", b =>
                {
                    b.HasOne("CistacApp.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_Payments_Bookings");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CistacApp.Models.Promotion", b =>
                {
                    b.HasOne("CistacApp.Models.Hotel", "Hotel")
                        .WithMany("Promotions")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_Promotion_Hotels");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("CistacApp.Models.Review", b =>
                {
                    b.HasOne("CistacApp.Models.Room", "Room")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Rooms");

                    b.HasOne("CistacApp.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CistacApp.Models.Room", b =>
                {
                    b.HasOne("CistacApp.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_Rooms_Hotels");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("CistacApp.Models.Staff", b =>
                {
                    b.HasOne("CistacApp.Models.Hotel", "Hotel")
                        .WithMany("Staff")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_Staff_Hotels");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("CistacApp.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CistacApp.Models.Hotel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Promotions");

                    b.Navigation("Rooms");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CistacApp.Models.Payment", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CistacApp.Models.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CistacApp.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
